In [21]:
import pandas as pd

In [22]:
data = pd.read_excel('Project Data.xlsx', index_col=0)

In [23]:
data.head()

,Age,Gender,City of Residence,Profession,Insurance Provider,Family History,Education Level,Marital Status,Visit Date,Department,Consultation Duration,Satisfaction Level,Approximate Annual Income,Consultation Price,Insurance Coverage
Patient ID,,,,,,,,,,,,,,,
1482,65.0,Female,Birmingham,Retired,NaN,Heart Disease,Master,Divorced,2024-02-22,Endocrinology,110,2,38839.0,293.014042,0.0
1482,65.0,Female,Birmingham,Retired,NaN,Heart Disease,Master,Divorced,2024-01-21,Emergency,76,4,52219.0,287.208982,0.0
1482,65.0,Female,Birmingham,Retired,NaN,Heart Disease,Master,Divorced,2024-06-13,Neurology,17,5,41491.0,241.254507,0.0
1482,65.0,Female,Birmingham,Retired,NaN,Heart Disease,Master,Divorced,2024-03-24,Emergency,15,3,34944.0,221.177483,0.0
1482,65.0,Female,Birmingham,Retired,NaN,Heart Disease,Master,Divorced,2024-03-19,Neurology,99,1,39248.0,219.743794,0.0

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10008 entries, 1482 to 1012
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        9952 non-null   float64
 1   Gender                     10008 non-null  object
 2   City of Residence          10008 non-null  object
 3   Profession                 10008 non-null  object
 4   Insurance Provider         8098 non-null   object
 5   Family History             8015 non-null   object
 6   Education Level            9979 non-null   object
 7   Marital Status             10008 non-null  object
 8   Visit Date                 10008 non-null  datetime64[ns]
 9   Department                 10008 non-null  object
 10  Consultation Duration      10008 non-null  int64
 11  Satisfaction Level         10008 non-null  int64
 12  Approximate Annual Income  9854 non-null   float64
 13  Consultation Price         10008 non-null  float64
 14  Insurance Coverage         9958 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(8)
memory usage: 1.2+ MB

In [25]:
patients_with_nan_age = data.index[data['Age'].isna()].unique()

inspect all cells of those patients and see if they have their age associated

In [26]:
patients_rows = data.loc[data.index.isin(patients_with_nan_age)]
ages_of_patients = patients_rows.groupby(patients_rows.index)['Age'] \
                                      .apply(lambda x: x.dropna().iloc[0])
ages_of_patients

Patient ID
1009    20.0
1012     7.0
1023    82.0
1029    16.0
1031    71.0
1036    78.0
1048    98.0
1051    29.0
1057    42.0
1061    42.0
1065    55.0
1070    93.0
1084    98.0
1103    65.0
1108    57.0
1109     2.0
1112    94.0
1117    79.0
1118    52.0
1125    65.0
1128    91.0
1139    35.0
1144    89.0
1154    48.0
1175    82.0
1213    29.0
1232    18.0
1234    14.0
1251    93.0
1258    27.0
1260    52.0
1274    74.0
1276    98.0
1280    30.0
1286    59.0
1287    68.0
1294    89.0
1303    34.0
1304     0.0
1307    34.0
1325    10.0
1328    46.0
1333     0.0
1340    51.0
1356    51.0
1360     1.0
1365    99.0
1387    15.0
1390    12.0
1419    54.0
1426    60.0
1492    43.0
1495    23.0
Name: Age, dtype: float64

In [27]:
for patient in patients_with_nan_age:
   age_to_fill_in_with = ages_of_patients.get(patient)
   data.loc[patient, 'Age'] = data.loc[patient,'Age'].fillna(age_to_fill_in_with)

In [28]:
data[data['Age'].isna()]

Empty DataFrame
Columns: [Age, Gender, City of Residence, Profession, Insurance Provider, Family History, Education Level, Marital Status, Visit Date, Department, Consultation Duration, Satisfaction Level, Approximate Annual Income, Consultation Price, Insurance Coverage]
Index: []

No missing values on age now.

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10008 entries, 1482 to 1012
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        10008 non-null  float64
 1   Gender                     10008 non-null  object
 2   City of Residence          10008 non-null  object
 3   Profession                 10008 non-null  object
 4   Insurance Provider         8098 non-null   object
 5   Family History             8015 non-null   object
 6   Education Level            9979 non-null   object
 7   Marital Status             10008 non-null  object
 8   Visit Date                 10008 non-null  datetime64[ns]
 9   Department                 10008 non-null  object
 10  Consultation Duration      10008 non-null  int64
 11  Satisfaction Level         10008 non-null  int64
 12  Approximate Annual Income  9854 non-null   float64
 13  Consultation Price         10008 non-null  float64
 14  Insurance Coverage         9958 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(8)
memory usage: 1.5+ MB

In [32]:
patients_with_nan_insurance_provider = data.index[data['Insurance Provider'].isna()].unique()

In [34]:
patients_rows_insurance = data.loc[data.index.isin(patients_with_nan_insurance_provider)]
insurance_provider_of_patients = (
    patients_rows_insurance
    .groupby(level=0)['Insurance Provider']
    .apply(lambda x: x.dropna().iloc[0] if x.dropna().size > 0 else None)
)
insurance_provider_of_patients

Patient ID
1005          None
1011          None
1012          None
1013          None
1014          None
           ...
1472          None
1482          None
1485    Provider D
1490    Provider D
1498    Provider D
Name: Insurance Provider, Length: 128, dtype: object

In [38]:
for patient in patients_with_nan_insurance_provider:
    provider = insurance_provider_of_patients.get(patient)
    if provider is not None:
        data.loc[patient, 'Insurance Provider'] = data.loc[patient, 'Insurance Provider'].fillna(provider)

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10008 entries, 1482 to 1012
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        10008 non-null  float64
 1   Gender                     10008 non-null  object
 2   City of Residence          10008 non-null  object
 3   Profession                 10008 non-null  object
 4   Insurance Provider         8148 non-null   object
 5   Family History             8015 non-null   object
 6   Education Level            9979 non-null   object
 7   Marital Status             10008 non-null  object
 8   Visit Date                 10008 non-null  datetime64[ns]
 9   Department                 10008 non-null  object
 10  Consultation Duration      10008 non-null  int64
 11  Satisfaction Level         10008 non-null  int64
 12  Approximate Annual Income  9854 non-null   float64
 13  Consultation Price         10008 non-null  float64
 14  Insurance Coverage         9958 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(8)
memory usage: 1.5+ MB